### PR TITLE
Added support for Volt templates.

### PR DESCRIPTION
**Pull request by dschissler**
I tested this by cloning my updated fork directly into my global node_modules directory and then running `npm install` in there.  Its a simple two line change to enable Volt support.

### CODE REVIEW

**Comment by dschissler** [comment]
@smhg @gmarty Can you guys take a look at this?

**Comment by smhg** [comment]
Does it make sense to add version 0.2.0 or should we go straight to 0.2.1? 0.2.1 code is not on GitHub?

**Comment by dschissler** [comment]
Oops I need to add 0.2.1 to github.  Somehow it didn't make it in the shuffle.  I'll check in a few hours if there are any differences.

**Comment by dschissler** [comment]
@smhg Also I created a permanent fork to [xgettext-webird](https://github.com/perchlayer/xgettext-webird) to ensure that I can immediately upgrade or add any parsers.

**Comment by dschissler** [comment]
I updated everything to 0.2.2.

**Pull request merged**
